#%RAML 1.0
title: Deloitte Exercise API
version: v1.0

types:
  customer: |
    {
      "id":123,
      "firstName":"John",
      "lastName":"Smith",
      "address":"1600 Pennsylvania Ave NW, Washington, DC 20500"
     }
    

/customers:
  get:
    description: Retrieve all customers
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "data": [
                  {
                  "id":123,
                  "firstName":"John",
                  "lastName":"Smith",
                  "address":"1600 Pennsylvania Ave NW, Washington, DC 20500"
                  }
                ],
                "success":true,
                "status":200
              }
/customer:
  post:
    description: Create a new customer
    body:
      application/json:
        properties:
          firstName:
            displayName: First Name
            type: string
            required: true
          lastName:
            displayName: Last Name
            type: string
            required: true
          address:
            displayName: Address
            type: string
            required: true
    responses:
      200:
        body:
          application/json:
            example: |
                {"data":{
                  "id":123,
                  "firstName":"John",
                  "lastName":"Smith",
                  "address":"1600 Pennsylvania Ave NW, Washington, DC 20500"
                },
                "success":true,
                 "status":200}
  /{customerId}:
    uriParameters:
        customerId: string
    put:
      description: Update customer information
      body:
       application/json:
          properties:
            firstName:
              displayName: First Name
              type: string
              required: false
            lastName:
              displayName: Last Name
              type: string
              required: false
            address:
              displayName: Address
              type: string
              required: false
      responses:
        200:
          body:
            application/json:
              example: |
                {"data":{
                  "id":"123",
                  "firstName":"John",
                  "lastName":"Smith",
                  "address":"1600 Pennsylvania Ave NW, Washington, DC 20500"
                },
                "success":true,
                 "status":200}
        204:
          body:
            application/json:
              example: |
                {"success":true,
                 "status":204
                }
    delete:
      description: Delete customer 
      responses:
        204:
          body:
            application/json:
              example: |
                {"success":true,,
                 "status":204}
          
